-- Auto-generated by dbt-index. Query with:
--   duckdb -cmd ".read views.sql"

CREATE SCHEMA IF NOT EXISTS dbt;
CREATE SCHEMA IF NOT EXISTS dbt_rt;

CREATE OR REPLACE VIEW dbt.generation AS SELECT * FROM read_parquet('dbt.generation.parquet');
CREATE OR REPLACE VIEW dbt.project AS SELECT * FROM read_parquet('dbt.project.parquet');
CREATE OR REPLACE VIEW dbt.packages AS SELECT * FROM read_parquet('dbt.packages.parquet');
CREATE OR REPLACE VIEW dbt.project_vars AS SELECT * FROM read_parquet('dbt.project_vars.parquet');
CREATE OR REPLACE VIEW dbt.project_env_vars AS SELECT * FROM read_parquet('dbt.project_env_vars.parquet');
CREATE OR REPLACE VIEW dbt.nodes AS SELECT * FROM read_parquet('dbt.nodes.parquet');
CREATE OR REPLACE VIEW dbt.node_columns AS SELECT * FROM read_parquet('dbt.node_columns.parquet');
CREATE OR REPLACE VIEW dbt.edges AS SELECT * FROM read_parquet('dbt.edges.parquet');
CREATE OR REPLACE VIEW dbt.column_lineage AS SELECT * FROM read_parquet('dbt.column_lineage.parquet');
CREATE OR REPLACE VIEW dbt.node_input_files AS SELECT * FROM read_parquet('dbt.node_input_files.parquet');
CREATE OR REPLACE VIEW dbt.test_metadata AS SELECT * FROM read_parquet('dbt.test_metadata.parquet');
CREATE OR REPLACE VIEW dbt.exposures AS SELECT * FROM read_parquet('dbt.exposures.parquet');
CREATE OR REPLACE VIEW dbt.metrics AS SELECT * FROM read_parquet('dbt.metrics.parquet');
CREATE OR REPLACE VIEW dbt.groups AS SELECT * FROM read_parquet('dbt.groups.parquet');
CREATE OR REPLACE VIEW dbt.macros AS SELECT * FROM read_parquet('dbt.macros.parquet');
CREATE OR REPLACE VIEW dbt.semantic_models AS SELECT * FROM read_parquet('dbt.semantic_models.parquet');
CREATE OR REPLACE VIEW dbt.semantic_entities AS SELECT * FROM read_parquet('dbt.semantic_entities.parquet');
CREATE OR REPLACE VIEW dbt.semantic_measures AS SELECT * FROM read_parquet('dbt.semantic_measures.parquet');
CREATE OR REPLACE VIEW dbt.semantic_dimensions AS SELECT * FROM read_parquet('dbt.semantic_dimensions.parquet');
CREATE OR REPLACE VIEW dbt.time_spines AS SELECT * FROM read_parquet('dbt.time_spines.parquet');
CREATE OR REPLACE VIEW dbt.semantic_relationships AS SELECT * FROM read_parquet('dbt.semantic_relationships.parquet');
CREATE OR REPLACE VIEW dbt.saved_queries AS SELECT * FROM read_parquet('dbt.saved_queries.parquet');
CREATE OR REPLACE VIEW dbt.unit_tests AS SELECT * FROM read_parquet('dbt.unit_tests.parquet');
CREATE OR REPLACE VIEW dbt.docs AS SELECT * FROM read_parquet('dbt.docs.parquet');
CREATE OR REPLACE VIEW dbt.catalog_tables AS SELECT * FROM read_parquet('dbt.catalog_tables.parquet');
CREATE OR REPLACE VIEW dbt.catalog_stats AS SELECT * FROM read_parquet('dbt.catalog_stats.parquet');
CREATE OR REPLACE VIEW dbt.column_stats AS SELECT * FROM read_parquet('dbt.column_stats.parquet');
CREATE OR REPLACE VIEW dbt.sample_data AS SELECT * FROM read_parquet('dbt.sample_data.parquet');
CREATE OR REPLACE VIEW dbt.source_freshness AS SELECT * FROM read_parquet('dbt.source_freshness.parquet');
CREATE OR REPLACE VIEW dbt.context AS SELECT * FROM read_parquet('dbt.context.parquet');
CREATE OR REPLACE VIEW dbt.context_terms AS SELECT * FROM read_parquet('dbt.context_terms.parquet');
CREATE OR REPLACE VIEW dbt.context_links AS SELECT * FROM read_parquet('dbt.context_links.parquet');

CREATE OR REPLACE VIEW dbt_rt.invocations AS SELECT * FROM read_parquet('dbt_rt.invocations.parquet');
CREATE OR REPLACE VIEW dbt_rt.invocation_nodes AS SELECT * FROM read_parquet('dbt_rt.invocation_nodes.parquet');
CREATE OR REPLACE VIEW dbt_rt.run_results AS SELECT * FROM read_parquet('dbt_rt.run_results.parquet');
CREATE OR REPLACE VIEW dbt_rt.diagnostics AS SELECT * FROM read_parquet('dbt_rt.diagnostics.parquet');
CREATE OR REPLACE VIEW dbt_rt.adapter_queries AS SELECT * FROM read_parquet('dbt_rt.adapter_queries.parquet');
CREATE OR REPLACE VIEW dbt_rt.test_failures AS SELECT * FROM read_parquet('dbt_rt.test_failures.parquet');

CREATE OR REPLACE VIEW dbt_rt.run_results_latest AS
SELECT * FROM dbt_rt.run_results
WHERE NOT (status = 'error' AND execution_time = 0)
QUALIFY ROW_NUMBER() OVER (PARTITION BY unique_id ORDER BY created_at DESC) = 1;

CREATE OR REPLACE VIEW dbt_rt.dag_validity AS
WITH latest AS (
    SELECT r.unique_id, r.status, r.invocation_id, i.generated_at
    FROM dbt_rt.run_results r
    JOIN dbt_rt.invocations i ON r.invocation_id = i.invocation_id
    QUALIFY ROW_NUMBER() OVER (PARTITION BY r.unique_id ORDER BY r.created_at DESC) = 1
)
SELECT
    child.unique_id, child.status,
    child.generated_at AS child_built_at,
    parent.unique_id AS parent_unique_id,
    parent.generated_at AS parent_built_at,
    child.generated_at >= parent.generated_at AS parent_is_fresh
FROM latest child
LEFT JOIN dbt.edges e ON e.child_unique_id = child.unique_id
LEFT JOIN latest parent ON e.parent_unique_id = parent.unique_id;

CREATE OR REPLACE VIEW dbt_rt.node_status AS
SELECT
    n.unique_id, n.name, n.resource_type,
    n.ingested_at AS parsed_at, n.compiled_at,
    r.created_at AS run_at, r.invocation_id AS run_invocation_id,
    r.status AS run_status, r.execution_time AS run_execution_time, r.message AS run_message,
    CASE
        WHEN r.created_at IS NOT NULL AND n.compiled_at IS NOT NULL AND r.created_at >= n.compiled_at THEN 'run'
        WHEN n.compiled_at IS NOT NULL THEN 'compiled'
        ELSE 'parsed'
    END AS effective_phase,
    CASE
        WHEN n.compiled_at IS NOT NULL AND n.ingested_at > n.compiled_at THEN true
        WHEN r.created_at IS NOT NULL AND n.compiled_at IS NOT NULL AND n.compiled_at > r.created_at THEN true
        ELSE false
    END AS is_stale
FROM dbt.nodes n
LEFT JOIN dbt_rt.run_results_latest r ON n.unique_id = r.unique_id;

CREATE OR REPLACE VIEW dbt.nodes_enriched AS
SELECT
    n.*, r.status AS last_run_status, r.execution_time AS last_execution_time,
    r.invocation_id AS last_invocation_id,
    ct.table_type AS catalog_table_type, ct.table_owner AS catalog_owner
FROM dbt.nodes n
LEFT JOIN dbt_rt.run_results_latest r ON n.unique_id = r.unique_id
LEFT JOIN dbt.catalog_tables ct ON n.unique_id = ct.unique_id;

CREATE OR REPLACE VIEW dbt.tests_enriched AS
SELECT
    n.unique_id, n.name AS test_name,
    tm.test_name AS test_type, tm.test_namespace, tm.column_name,
    tm.attached_node, tm.severity, tm.kwargs,
    target.name AS target_node_name, target.resource_type AS target_resource_type,
    r.status AS last_run_status, r.message AS last_run_message, r.failures AS last_run_failures,
    tf.failure_rows
FROM dbt.nodes n
JOIN dbt.test_metadata tm ON n.unique_id = tm.unique_id
LEFT JOIN dbt.nodes target ON tm.attached_node = target.unique_id
LEFT JOIN dbt_rt.run_results_latest r ON n.unique_id = r.unique_id
LEFT JOIN dbt_rt.test_failures tf ON n.unique_id = tf.unique_id AND r.invocation_id = tf.invocation_id
WHERE n.resource_type IN ('test');

-- Parse-safe views: columns are enumerated (never `SELECT *`) so a
-- dbt.nodes column that is never populated at parse cannot leak into
-- these views as a silent NULL. Per-resource-type views select from
-- dbt.graph_nodes, not dbt.nodes directly, so they inherit the guarantee.
CREATE OR REPLACE VIEW dbt.graph_nodes AS
SELECT
    unique_id, name, resource_type, package_name, file_path, original_file_path,
    fqn, alias, checksum, description, raw_code, database_name, schema_name,
    relation_name, identifier, enabled, materialized, config, access_level,
    group_name, contract_enforced, version, latest_version, deprecation_date,
    primary_key, patch_path, tags, meta, source_name, source_description,
    loader, loaded_at_field, ingested_at
FROM dbt.nodes;

CREATE OR REPLACE VIEW dbt.models AS SELECT * FROM dbt.graph_nodes WHERE resource_type = 'model';
CREATE OR REPLACE VIEW dbt.seeds AS SELECT * FROM dbt.graph_nodes WHERE resource_type = 'seed';
CREATE OR REPLACE VIEW dbt.tests AS SELECT * FROM dbt.graph_nodes WHERE resource_type = 'test';
CREATE OR REPLACE VIEW dbt.snapshots AS SELECT * FROM dbt.graph_nodes WHERE resource_type = 'snapshot';
CREATE OR REPLACE VIEW dbt.sources AS SELECT * FROM dbt.graph_nodes WHERE resource_type = 'source';
CREATE OR REPLACE VIEW dbt.analyses AS SELECT * FROM dbt.graph_nodes WHERE resource_type = 'analysis';
CREATE OR REPLACE VIEW dbt.operations AS SELECT * FROM dbt.graph_nodes WHERE resource_type IN ('operation', 'sql_operation');
CREATE OR REPLACE VIEW dbt.functions AS SELECT * FROM dbt.graph_nodes WHERE resource_type = 'function';
CREATE OR REPLACE VIEW dbt.checks AS SELECT * FROM dbt.graph_nodes WHERE resource_type = 'check';

-- dbt.columns: dbt.node_columns restricted to columns populated at parse
-- (catalog/inferred-type/expression columns require static analysis or
-- `dbt docs generate` and are NULL until then).
CREATE OR REPLACE VIEW dbt.columns AS
SELECT unique_id, column_name, declared_type, description, tags, ingested_at
FROM dbt.node_columns;
