version: 1

sources: 
  - name: eth
    quoting: 
      database: true
      schema: true
    database: ETH
    schema: ETH_SCHEMA
    tables: 
      - name: contracts
        identifier: cnt
      - name: token_transfers
      - name: transactions
      - name: contracts_clone
